### ISSUE TITLE
report.gen_report fails if there is only one channel type

### ISSUE THREAD

**Issue by woolrich** [OHBA-analysis/oslpy#60]
report.gen_report fails if there is only one channel type. Traceback below.

Similar problem in plot_channel_dists()

----------

Traceback (most recent call last):

  File "<ipython-input-2-a23e3c699340>", line 171, in <cell line: 167>
    report.gen_report(preproc_fif_files, outdir=preproc_dir)
  File "/Users/woolrich/oslpy/osl/report/raw_report.py", line 182, in gen_report
    data = gen_html_data(raw, ica, outdir, level)
  File "/Users/woolrich/oslpy/osl/report/raw_report.py", line 112, in gen_html_data
    data['plt_temporalsumsq'] = plot_channel_time_series(raw, savebase)
  File "/Users/woolrich/oslpy/osl/report/raw_report.py", line 279, in plot_channel_time_series
    ax[row].plot(t, ss)
TypeError: 'AxesSubplot' object is not subscriptable

**Comment by cgohil8** [comment]
The line numbers in the traceback don't match the main branch which suggests you might be using an old branch. 

This issue should be resolved here: https://github.com/OHBA-analysis/oslpy/blob/main/osl/report/raw_report.py#L315-L316.

I've just tested the function when the raw object only contains one type (EEG) and it seems to work fine so I'm going to close this. Please reopen if this issue arises again.
